// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { projects } from "npm:@/data/projects";
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List \u041Cer Yerevan city projects. Optionally filter by stage (sponsorship or concept).",
  inputSchema: {
    stage: z.enum(["sponsorship", "concept"]).optional().describe("Filter by project stage.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ stage }) => {
    const items = projects.filter((p) => stage ? p.stage === stage : true).map((p) => ({
      id: p.id,
      title: p.title,
      titleEn: p.titleEn,
      stage: p.stage,
      location: p.location,
      locationEn: p.locationEn,
      budget: p.budget,
      displayBudget: p.displayBudget,
      address: p.address
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { projects: items, count: items.length }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { projects as projects2 } from "npm:@/data/projects";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project details",
  description: "Get full details for a single \u041Cer Yerevan project by its id.",
  inputSchema: {
    id: z2.string().min(1).describe("Project id, e.g. as returned by list_projects.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ id }) => {
    const p = projects2.find((x) => x.id === id);
    if (!p) {
      return {
        content: [{ type: "text", text: `No project with id "${id}"` }],
        isError: true
      };
    }
    const { image, gallery, ...rest } = p;
    const details = { ...rest, galleryCount: gallery?.length ?? 0 };
    return {
      content: [{ type: "text", text: JSON.stringify(details, null, 2) }],
      structuredContent: { project: details }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "mer-yerevan-mcp",
  title: "\u041Cer Yerevan MCP",
  version: "0.1.0",
  instructions: "Tools for the \u041Cer Yerevan city platform. Use `list_projects` to browse sponsorship and concept projects, and `get_project` to fetch full details for a specific project by id.",
  tools: [list_projects_default, get_project_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
